# Generated by Django 5.0.6 on 2024-07-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
