# Generated by Django 5.0.4 on 2024-05-14 23:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='reward_images')),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
