# Generated by Django 5.0.6 on 2024-07-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_reward_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='reward',
            name='category',
        ),
        migrations.AddField(
            model_name='reward',
            name='category_name',
            field=models.CharField(default='Plantas', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
