# Generated by Django 5.0.4 on 2024-05-30 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='recycling_transaction',
            new_name='transaction',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_code_image',
        ),
        migrations.RemoveField(
            model_name='userpoints',
            name='recycling_transaction',
        ),
        migrations.AddField(
            model_name='userpoints',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qr_codes.recyclingtransaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recyclable',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recyclingtransaction',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='transaction_type',
            field=models.CharField(max_length=255),
        ),
    ]
