# Generated by Django 5.0.4 on 2024-06-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0002_rename_recycling_transaction_qrcode_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoints',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qr_codes.recyclingtransaction'),
        ),
    ]
