# Generated by Django 5.0.6 on 2024-07-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0004_category_recyclable_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclingtransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='recyclingtransaction',
            name='user_id',
            field=models.CharField(default='17', max_length=255, verbose_name='User ID'),
        ),
    ]
