# Generated by Django 5.0.6 on 2024-07-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0005_remove_recyclingtransaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingtransaction',
            name='recyclable',
            field=models.CharField(max_length=255),
        ),
    ]
